Cluster View
metricq/metricq-wizard-frontend pull request #61
Opened 2022-12-20 17:20 UTC by bmario

This is such a big chungus refactoring that I don't even know where to start. 

Major changes:

- Merged "Source Overview" and "Client Overview", together with new information into the Cluster View
- Refactored Client JSON raw configuration, especially since it has now a list of backup configurations
- Touched up the design of the "Metric Overview" page and renamed it into "Metric Workshop"
- Added the completely new "Metric Library", which allows to see the source, sink, metadata and live date points of one metric in one page

2023-01-23 17:44 UTC, tilsche requested changes
very far away from completion :/

2023-01-23 17:44 UTC, tilsche commented on pages/client/list.vue
> +      await sleep(10000)
Magic number as constant

2023-01-23 17:44 UTC, tilsche commented on pages/client/list.vue
> +    await Client.api().get('/clients', { persistsBy: 'insert' })
Document why the order is important here!

2023-01-23 17:44 UTC, tilsche commented on pages/metric/_metricId.vue
> +  },
I just saw this exact code in `list.vue` can't we deduplicate this?

2023-01-23 17:44 UTC, tilsche commented on pages/client/edit_json/_clientId/index.vue
> +                data-enable-grammarly="false"
:vomiting_face:

2023-01-25 08:42 UTC, tilsche requested changes

2023-01-25 15:47 UTC, tilsche requested changes

2023-01-25 15:47 UTC, tilsche commented on nuxt.config.js
> +    },
Explanation comment what this does and why it is necessary...

Sure I'm a nuxt-noob, but even after reading the documentation I'm clueless.

2023-01-25 15:47 UTC, tilsche commented on pages/client/_clientId.vue
> +                  </b-list-group>
I know where you copied that from, but I think that's pretty bad UI design... Just put a spinner, placeholder text or whatever that actually conveys what's happening.

2023-01-25 15:47 UTC, tilsche commented on pages/client/_clientId.vue
> +                  </b-list-group>
Now the 10 line magic number mystic placeholder is even copied across the code :see_no_evil:

2023-01-25 15:47 UTC, tilsche commented on pages/client/_clientId.vue
> +    },
Can this be moved to `client.producedMetrics` on the object?

2023-01-25 15:47 UTC, tilsche commented on pages/client/_clientId.vue
> +  },
What in the name of the boilerplate goddess.... That can't be necessary, can it?

2023-01-25 15:47 UTC, tilsche commented on pages/client/edit_json/_clientId/index.vue
> +                  :obj-data="jsonData"
Necessary? The documentation doesn't explain that.

2023-01-25 15:47 UTC, tilsche commented on pages/client/edit_json/_clientId/index.vue
> +        this.$refs.saveButton.disabled = true
Not a huge fan of those manipulations in the handler when we have the reactive framework. Could see it better to set a `jsonDataValid` instead that is then used in the respective tags. Possibly even as a computed property, not sure about that though.

2023-01-25 15:47 UTC, tilsche commented on pages/client/edit_json/_clientId/index.vue
> +                  @click="onBackupClick(backup)"
```suggestion
                  v-for="backupId in backupIds"
                  :key="backupId"
                  button
                  @click="onBackupClick(backupId)"
```

Consistency with other code and it's clear that we're not handling complex objects here.

2023-01-25 15:47 UTC, tilsche commented on pages/client/list.vue
> +                <span v-if="data.item.discoverTime">
Doesn't look like you need/want an actual `<span>` HTML tag here, do you? If not, use `<template ...` instead.

2023-01-25 15:47 UTC, tilsche commented on plugins/chartkick.js
> +    useUTC: false,
Why?

2023-01-25 15:47 UTC, tilsche commented on plugins/moment-filter.js
> +  }
I see what you did there, but it's so evil that I want it as a comment as well.

2023-01-25 15:47 UTC, tilsche commented on pages/metric/_metricId.vue
> +                          :client="getMetricSource(selectedMetric.source)"
Maybe the client-actions themselves should react to having a `null`/`undefined` client. Possible with an `allowUndefined` property.

2023-01-26 10:05 UTC, tilsche requested changes

2023-01-26 10:05 UTC, tilsche commented on pages/metric/configure.vue
> +  },
Please move to `async fetch`

2023-01-27 12:21 UTC, bmario commented on pages/client/edit_json/_clientId/index.vue
> +                  :obj-data="jsonData"
There are a billion vue json edit(or) packages. We're using vue-json-edit and use it like they have documented it: https://github.com/jinkin1995/vue-json-edit/blob/master/README.md?plain=1#L52

2023-01-27 12:24 UTC, bmario commented on plugins/chartkick.js
> +    useUTC: false,
Because I want timestamps in the graph to be local time:

https://api.highcharts.com/highcharts/time.useUTC

2023-01-27 14:51 UTC, bmario commented on pages/metric/_metricId.vue
> +          })
Turns out, the metricq-sink-websocket filters out non-finite values, so let's get rid of it for now.

2023-02-01 15:57 UTC, merged