Webview integration
metricq/metricq-wizard-frontend pull request #81
Opened 2023-05-26 12:17 UTC by bmario

Add a MetricQ Webview link in the navbar, in the metric detail page, as well as
a button to open all selected metrics in the metric workshop.

Closes #44

2023-05-26 13:45 UTC, tilsche requested changes

2023-05-26 13:45 UTC, tilsche commented on Dockerfile
> +LABEL maintainer="mario.bielert@tu-dresden.de"
I found your smuggle commit!

2023-05-26 13:45 UTC, tilsche commented on pages/metric/_metricId.vue
> +                  <b-col></b-col>
So we're using a fake bootstrap based table with a single row and an empty column to start. Looks like solid modern web technology. Amirite?

2023-05-26 13:45 UTC, tilsche commented on pages/metric/_metricId.vue
> +                        '#.now-1h*now*' +
I just had a vision that there was a cool default where it would show the full scope of the recorded data instead... Must have been something in my tea.

2023-05-26 13:45 UTC, tilsche commented on pages/metric/_metricId.vue
> +                      <b-icon-graph-up /> Open in Webview<sup>
I believe the rarely used but official capitalization is

```suggestion
                      <b-icon-graph-up />Open in WebView<sup>
```

2023-05-26 13:45 UTC, tilsche commented on pages/metric/configure.vue
> +                Webview<sup>
```suggestion
                WebView<sup>
```

2023-05-26 13:45 UTC, tilsche commented on pages/metric/configure.vue
> +              Such metrics cannot be opened in Webview.
```suggestion
              Such metrics cannot be opened in WebView.
```

2023-05-26 13:45 UTC, tilsche commented on pages/metric/configure.vue
> +    },
I would strongly prefer there to be a *single* place where these links are generated (i.e. knowledge about the default time and encoding of the anchor).

2023-06-03 09:00 UTC, bmario commented on pages/metric/_metricId.vue
> +                        '#.now-1h*now*' +
Is that a thing in webview URL parsing, or is it just a fever dream?

2023-06-04 09:31 UTC, tilsche commented on pages/metric/_metricId.vue
> +                        '#.now-1h*now*' +
Fever dream.

2024-03-19 16:01 UTC, merged